Serve: # 服务配置
  RunMode: "debug" # release 为生产模式
  Address: ":9090" # 监听端口
  ReadTimeout: 5s
  WriteTimeout: 5s
  DefaultContextTimeout: 30s #默认超时时间
App:
  Name: "mognolia"
  Version: "1.0"
Log: # 日志配置文件
  Level: debug
  LogSavePath: "storage/Applogs/" # 日志保存路径
  HighLevelFile: error          # 高级别日志文件名
  LowLevelFile: info          # 低级别文件名s
  LogFileExt: .log          # 日志文件后缀
  MaxSize: 10 # 日志文件最大大小
  MaxAge: 30 # 日志文件最大保存天数
  MaxBackups: 7 # 最大备份数
  Compress: false # 是否压缩
Mysql:
  user: "root"
  password: "zxz123456"
  host: "127.0.0.1"
  port: 3306
  dbName: "gin-vue-ttms"
Redis:
  addr: "127.0.0.1:6379"
  password: "123456"
  poolSize: 20
  CacheTime: 1h
Rule:
  delUserTime: 60s
  delCodeTime: 120s
  DefaultAccountAvatar: "http://lycmall.lyc666.xyz/chat/first.jpg"
  DefaultClientTimeout: 20s
  DefaultPagePerNum: 10
  FileMaxSize: 1024000
  DefaultInsertDataNum : 50
  DefaultUserFavorPage: 5 # 用户关注电影的总页数
  DefaultUserFavorSize: 10 #用户关注电影每页的个数
  LockTicketTime: 15m #锁票的超时时间
  LockOrderTime: 15m #订单超时的时间
SMTPInfo:
  host: "smtp.qq.com"
  port: 465
  userName: "1197285120@qq.com"
  password: "***" #密码
  isSSL: true
  from: "1197285120@qq.com" #发件人
  to: #接收人
    - "1197285120@qq.com"
Work: #工作池配置
  taskChanCapacity: 50 # 任务队列容量
  workerChanCapacity: 50 # 工作队列容量
  workerNum: 10 # 工作池数量
Token:
  key: "s1Qimd1a6lqEiFRh56KfA25gXoY2MEyF" #长度得是32位
  accessToken: 24h
  refreshToken: 48h
  AuthType: "x_token"
  AuthKey: "Claims"
AliyunOSS:
  Endpoint: "http://oss-cn-hangzhou.aliyuncs.com"
  AccessKeyId: "***"
  AccessKeySecret: "***"
  BucketName: "lycmall2"
  BucketUrl: "ttms"
  BasePath: "http://lycmall.lyc666.xyz"
Auto:
  AutoFlushReadCount2DBTime: 10m
  PeopleFavorToCacheTime: 10m
  DeleteOutTimeTime: 10m